kind: Deployment
apiVersion: apps/v1
metadata:
   name: mariadb
spec:
   replicas: 1
   selector:
      matchLabels:
         app: mariadb
   template:
      metadata:
         labels:
            app: mariadb
      spec:
         containers:
            - name: mariadb
              image: mariadb:latest
              volumeMounts:
              - mountPath: /var/lib/mysql
                name: mariadb-data
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: "specify-a-password"
              - name: MYSQL_USER
                value: "my-user"
              - name: MYSQL_PASSWORD
                value: "specify-a-password"
              - name: MYSQL_DATABASE
                value: "my-db"
         volumes:
         - name: mariadb-data
           hostPath:
              path: /mnt/data/mariadb-data
              type: Directory

---
apiVersion: v1
kind: Service
metadata:
   name: mariadb
   labels:
      app: mariadb
spec:
   ports:
      - port: 3306
        name: mariadb
   selector:
      app: mariadb
